### ISSUE TITLE
Imports of `python_multipart` by other packages is broken in 0.0.14

### ISSUE THREAD

**Issue by ebr** [Kludex/python-multipart#173]
This started happening as soon as 0.0.14 was released:
```
Traceback (most recent call last):
  File "/opt/invokeai/.venv/bin/invokeai-web", line 8, in <module>
    sys.exit(run_app())
             ^^^^^^^^^
  File "/opt/invokeai/invokeai/app/run_app.py", line 10, in run_app
    from invokeai.app.api_app import invoke_api
  File "/opt/invokeai/invokeai/app/api_app.py", line 26, in <module>
    from invokeai.app.api.routers import (
  File "/opt/invokeai/invokeai/app/api/routers/images.py", line 29, in <module>
    @images_router.post(
     ^^^^^^^^^^^^^^^^^^^
  File "/opt/invokeai/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 944, in decorator
    self.add_api_route(
  File "/opt/invokeai/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 883, in add_api_route
    route = route_class(
            ^^^^^^^^^^^^
  File "/opt/invokeai/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 519, in __init__
    self.body_field = get_body_field(dependant=self.dependant, name=self.unique_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/invokeai/.venv/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 817, in get_body_field
    check_file_field(final_field)
  File "/opt/invokeai/.venv/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 100, in check_file_field
    raise RuntimeError(multipart_not_installed_error) from None
RuntimeError: Form data requires "python-multipart" to be installed.
You can install "python-multipart" with:

pip install python-multipart
```

experiencing this right now while working on InvokeAI, but assuming this affects all packages that use `fastapi`, possibly `starlette`, and maybe more.

downgrading to v0.0.12 fixed the issue.

**Comment by Kludex** [comment]
Please check latest issues instead of creating new ones.

**Comment by ebr** [comment]
I did, there was no latest issue on this topic. I now see there is a closed one. thanks.
